# dist: trusty

language: php

php:
- "5.6"
- "7.0"
- "7.1"

matrix:
  fast_finish: true
  allow_failure:
  - php: "5.6"

install:
- phpenv rehash
- composer install

script:
- phpunit -c phpunit.xml.dist
- example/demo meta --zsh commit arg 0 suggestions
- example/demo meta --zsh commit arg 1 valid-values
- example/demo zsh --bind demo > zsh

after_success:
  - php vendor/bin/coveralls -v

cache:
  apt: true
  directories:
  - vendor

notifications:
  email:
    on_success: change # default: always
    on_failure: change # default: always
  slack:
    secure: G/7MNT2ZQirPcxX4ui1qn7mfDi29FPIY1ThN4c+KMp5IMLoFtHmrs+3hdCXLQC4mYkWrqLQVQpqRZb92qemZAbRpyaV+1g6IDFzunia95aF2eDRD73TQCNDrKkxhBi69FGo3ToOiB1wTtX/WYLFfkfOmFI43Wu+5fTmvH2mOtIk=
